CREATE TABLE FOOSBALL.FOOSBALLUSER
(ID INTEGER NOT NULL AUTO_INCREMENT,
FIRSTNAME VARCHAR(40) NOT NULL,
LASTNAME VARCHAR(40) NOT NULL,
USERNAME VARCHAR(40) NOT NULL,
PASSWORD VARCHAR(40) NOT NULL,
LEVEL INTEGER,
ROLE VARCHAR(40),
PRIMARY KEY (ID));

CREATE TABLE FOOSBALL.TEAM
(ID INTEGER NOT NULL AUTO_INCREMENT,
NAME VARCHAR(40) NOT NULL,
PRIMARY KEY (ID));

