drop table FOOSBALL.FOOSBALLUSER;

CREATE TABLE FOOSBALL.FOOSBALLUSER(
id bigint auto_increment primary key, 
username varchar(50),
firstname varchar(50),
lastname varchar(50),
password varchar(1064),
level double,
ROLE VARCHAR(40),
team_id BIGINT);

drop table FOOSBALL.TEAM;

CREATE TABLE FOOSBALL.TEAM(
id bigint auto_increment primary key, 
teamname varchar(50) not null,
numberofgames int,
cumulativepoint int,
rank int);

ALTER TABLE FOOSBALL.FOOSBALLUSER ADD FOREIGN KEY (team_id) REFERENCES FOOSBALL.TEAM(id);

drop table FOOSBALL.USER_RATINGS;

CREATE TABLE FOOSBALL.USER_RATINGS(
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
RATING_USER_ID BIGINT,
RATED_USER_ID BIGINT,
RATING INT);

ALTER TABLE FOOSBALL.USER_RATINGS
ADD FOREIGN KEY (RATING_USER_ID)
REFERENCES FOOSBALL.FOOSBALLUSER(id);

ALTER TABLE FOOSBALL.USER_RATINGS
ADD FOREIGN KEY (RATED_USER_ID)
REFERENCES FOOSBALL.FOOSBALLUSER(id);

drop table FOOSBALL.MATCH;

CREATE TABLE FOOSBALL.MATCH(
id bigint auto_increment primary key,
firstTeam_id bigint,
secondTeam_id bigint,
firstScore int,
secondScore int);

INSERT INTO FOOSBALL.TEAM(ID, teamname) VALUES (1, 'TEAM 1');
INSERT INTO FOOSBALL.TEAM(ID, teamname) VALUES (2, 'TEAM 2');
INSERT INTO FOOSBALL.TEAM(ID, teamname) VALUES (3, 'TEAM 3');
INSERT INTO FOOSBALL.TEAM(ID, teamname) VALUES (4, 'TEAM 4');
INSERT INTO FOOSBALL.TEAM(ID, teamname) VALUES (5, 'TEAM 5');
INSERT INTO FOOSBALL.TEAM(ID, teamname) VALUES (6, 'TEAM 6');
INSERT INTO FOOSBALL.TEAM(ID, teamname) VALUES (7, 'TEAM 7');
INSERT INTO FOOSBALL.TEAM(ID, teamname) VALUES (8, 'TEAM 8');
INSERT INTO FOOSBALL.TEAM(ID, teamname) VALUES (9, 'TEAM 9');
INSERT INTO FOOSBALL.TEAM(ID, teamname) VALUES (10, 'TEAM 10');
INSERT INTO FOOSBALL.TEAM(ID, teamname) VALUES (11, 'TEAM 11');
INSERT INTO FOOSBALL.TEAM(ID, teamname) VALUES (12, 'TEAM 12');
INSERT INTO FOOSBALL.TEAM(ID, teamname) VALUES (13, 'TEAM 13');
INSERT INTO FOOSBALL.TEAM(ID, teamname) VALUES (14, 'TEAM 14');
INSERT INTO FOOSBALL.TEAM(ID, teamname) VALUES (15, 'TEAM 15');
INSERT INTO FOOSBALL.TEAM(ID, teamname) VALUES (16, 'TEAM 16');
COMMIT;



